encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wikipedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("results", views.searchBox, name="results"),
    path("new-page", views.newPage, name="newPage"),
    path("edit-page", views.editPage, name="editPage"),
    path("random-page", views.randomPage, name="randomPage"),
    path("<str:entry>", views.entryPage, name="entryPage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django import forms
from . import util
import markdown
from django.contrib import messages
import random

class NewEntryForm(forms.Form):
    title = forms.CharField(label="New entry title")
    text = forms.CharField(label="New entry text")

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries() })

def entryPage(request, entry=""):
    if entry in util.list_entries():
        html = {
            'html': markdown.markdown(util.get_entry(entry)),
            "entry": entry
        }
        return render(request, "encyclopedia/entry-page.html", html)
    else:
        return HttpResponse("Entry does not exist")

def searchBox(request):
    if request.method == "POST":
        search = request.POST["q"]
        resultList = []
        for element in util.list_entries():
            if element.lower() == search.lower():
                return redirect("/{}" .format(element))
            if search.lower() in element.lower():
                resultList.append(element)
        if len(resultList) == 0:
            return HttpResponse("No results")
        else:
            return render(request, "encyclopedia/result-page.html", {"results": resultList})
    else:
        return redirect("/")
    
def newPage(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            text = form.cleaned_data["text"]
        else:
            return render(request, "encyclopedia/new-page.html", {"form": NewEntryForm()})
        if title in util.list_entries():
            return HttpResponse("Entry already exist")
        else:
            util.save_entry(title, text)
            return redirect("/{}" .format(title))
    else:
        return render(request, "encyclopedia/new-page.html", {"form": NewEntryForm()})
        
def editPage(request):
    if "redirect" in request.POST:
        entry = request.POST["entry"]
        text = util.get_entry(entry)
        return render(request, "encyclopedia/edit-page.html", {"text":text, "entry":entry})
    if "editText" in request.POST:
        newText = request.POST['newText']
        title = request.POST['title']
        util.save_entry(title, newText)
        return redirect("/{}" .format(title))
    else:
        return redirect("/")
    
def randomPage(request):
    randomEntry = random.choice(util.list_entries())
    return redirect("/{}" .format(randomEntry))

encyclopedia/templates/encyclopedia/edit-page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create new entry</h1>

    <div>
        <form action="{% url 'wikipedia:editPage' %}" method="post">
            {% csrf_token %}
            <textarea name="newText" rows="10" cols="50">{{ text }}</textarea>
            <input type="hidden" name="title" value="{{ entry }}">
            <button type="submit" name="editText">Edit entry</button>
        </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/entry-page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ entry }} information</h1>

    
    <div>
        {% load static %}
        {{ html | safe }}
    </div>
    <form action="{% url 'wikipedia:editPage' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="entry" value="{{ entry }}">
        <button type="submit" name="redirect">Edit entry</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wikipedia:results' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <input type="submit" hidden>
                </form>
                <div>
                    <a href="{% url 'wikipedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wikipedia:newPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wikipedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new-page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create new entry</h1>

    <div>
        <form action="{% url 'wikipedia:newPage' %}" method="post">
            {% csrf_token %}
            {% for f in form %}
                {{ f.label }} : {{ f }}
                <br>
            {% endfor %}
            <input type="submit">
        </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/result-page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for result in results %}
            <li><a href="/{{result}}">{{ result }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}